-- Create weekly_records table to track each user's record for each week
-- This provides an audit trail and allows easy recalculation of season totals

-- Create the table
CREATE TABLE IF NOT EXISTS weekly_records (
    id bigint generated by default as identity primary key,
    user_id uuid references profiles(id) not null,
    week_start date not null,
    week_end date not null,
    wins integer not null default 0,
    losses integer not null default 0,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
    
    -- Each user can only have one record per week
    UNIQUE(user_id, week_start)
);

-- Enable RLS
ALTER TABLE weekly_records ENABLE ROW LEVEL SECURITY;

-- Everyone can read weekly records
CREATE POLICY "Weekly records are viewable by everyone"
    ON weekly_records FOR SELECT
    USING (true);

-- Only service role can insert/update (done by automated scripts)
CREATE POLICY "Service role can insert weekly records"
    ON weekly_records FOR INSERT
    WITH CHECK (true);

CREATE POLICY "Service role can update weekly records"
    ON weekly_records FOR UPDATE
    USING (true);

-- Create index for faster lookups
CREATE INDEX idx_weekly_records_user_id ON weekly_records(user_id);
CREATE INDEX idx_weekly_records_week_start ON weekly_records(week_start);

-- Insert historical data (Weeks 1-3 from paper records)
-- Week 1: Nov 10-16, 2025
INSERT INTO weekly_records (user_id, week_start, week_end, wins, losses)
SELECT id, '2025-11-10', '2025-11-16', 4, 11 FROM profiles WHERE username = 'Jacoby'
ON CONFLICT (user_id, week_start) DO NOTHING;

INSERT INTO weekly_records (user_id, week_start, week_end, wins, losses)
SELECT id, '2025-11-10', '2025-11-16', 8, 7 FROM profiles WHERE username = 'Caden'
ON CONFLICT (user_id, week_start) DO NOTHING;

INSERT INTO weekly_records (user_id, week_start, week_end, wins, losses)
SELECT id, '2025-11-10', '2025-11-16', 6, 9 FROM profiles WHERE username = 'David '
ON CONFLICT (user_id, week_start) DO NOTHING;

-- Week 2: Nov 17-23, 2025
INSERT INTO weekly_records (user_id, week_start, week_end, wins, losses)
SELECT id, '2025-11-17', '2025-11-23', 12, 10 FROM profiles WHERE username = 'Jacoby'
ON CONFLICT (user_id, week_start) DO NOTHING;

INSERT INTO weekly_records (user_id, week_start, week_end, wins, losses)
SELECT id, '2025-11-17', '2025-11-23', 10, 12 FROM profiles WHERE username = 'Caden'
ON CONFLICT (user_id, week_start) DO NOTHING;

INSERT INTO weekly_records (user_id, week_start, week_end, wins, losses)
SELECT id, '2025-11-17', '2025-11-23', 14, 8 FROM profiles WHERE username = 'David '
ON CONFLICT (user_id, week_start) DO NOTHING;

-- Week 3: Nov 24-30, 2025
INSERT INTO weekly_records (user_id, week_start, week_end, wins, losses)
SELECT id, '2025-11-24', '2025-11-30', 39, 28 FROM profiles WHERE username = 'Jacoby'
ON CONFLICT (user_id, week_start) DO NOTHING;

INSERT INTO weekly_records (user_id, week_start, week_end, wins, losses)
SELECT id, '2025-11-24', '2025-11-30', 33, 34 FROM profiles WHERE username = 'Caden'
ON CONFLICT (user_id, week_start) DO NOTHING;

INSERT INTO weekly_records (user_id, week_start, week_end, wins, losses)
SELECT id, '2025-11-24', '2025-11-30', 35, 32 FROM profiles WHERE username = 'David '
ON CONFLICT (user_id, week_start) DO NOTHING;

-- Week 4: Dec 1-7, 2025 (calculate from confirmed totals)
-- Week 4 = Week 4 ending totals - Week 1-3 totals
-- Jacoby: 99-86 total, 55-49 paper = 44-37 week 4
-- Caden: 99-86 total, 51-53 paper = 48-33 week 4
-- David: 93-92 total, 55-49 paper = 38-43 week 4
INSERT INTO weekly_records (user_id, week_start, week_end, wins, losses)
SELECT id, '2025-12-01', '2025-12-07', 44, 37 FROM profiles WHERE username = 'Jacoby'
ON CONFLICT (user_id, week_start) DO NOTHING;

INSERT INTO weekly_records (user_id, week_start, week_end, wins, losses)
SELECT id, '2025-12-01', '2025-12-07', 48, 33 FROM profiles WHERE username = 'Caden'
ON CONFLICT (user_id, week_start) DO NOTHING;

INSERT INTO weekly_records (user_id, week_start, week_end, wins, losses)
SELECT id, '2025-12-01', '2025-12-07', 38, 43 FROM profiles WHERE username = 'David '
ON CONFLICT (user_id, week_start) DO NOTHING;

-- Week 5: Dec 8-14, 2025 (from database calculation)
INSERT INTO weekly_records (user_id, week_start, week_end, wins, losses)
SELECT id, '2025-12-08', '2025-12-14', 20, 7 FROM profiles WHERE username = 'Jacoby'
ON CONFLICT (user_id, week_start) DO NOTHING;

INSERT INTO weekly_records (user_id, week_start, week_end, wins, losses)
SELECT id, '2025-12-08', '2025-12-14', 13, 14 FROM profiles WHERE username = 'Caden'
ON CONFLICT (user_id, week_start) DO NOTHING;

INSERT INTO weekly_records (user_id, week_start, week_end, wins, losses)
SELECT id, '2025-12-08', '2025-12-14', 14, 13 FROM profiles WHERE username = 'David '
ON CONFLICT (user_id, week_start) DO NOTHING;

-- Verify the data
SELECT 
    p.username,
    wr.week_start,
    wr.week_end,
    wr.wins,
    wr.losses
FROM weekly_records wr
JOIN profiles p ON wr.user_id = p.id
ORDER BY wr.week_start, p.username;

-- Verify season totals match
SELECT 
    p.username,
    SUM(wr.wins) as calculated_wins,
    SUM(wr.losses) as calculated_losses,
    p.total_wins as stored_wins,
    p.total_losses as stored_losses,
    CASE 
        WHEN SUM(wr.wins) = p.total_wins AND SUM(wr.losses) = p.total_losses 
        THEN '✓ Match' 
        ELSE '✗ MISMATCH' 
    END as status
FROM weekly_records wr
JOIN profiles p ON wr.user_id = p.id
GROUP BY p.id, p.username, p.total_wins, p.total_losses
ORDER BY p.username;
