-- Create weekly_winners table to track who won each week
CREATE TABLE IF NOT EXISTS weekly_winners (
    id bigint generated by default as identity primary key,
    user_id uuid references profiles(id) not null,
    week_start date not null, -- Monday of the week
    week_end date not null, -- Sunday of the week
    wins integer not null default 0,
    losses integer not null default 0,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    unique(user_id, week_start)
);

-- Enable RLS for weekly_winners
ALTER TABLE weekly_winners ENABLE ROW LEVEL SECURITY;

-- Create policies for weekly_winners
CREATE POLICY "Weekly winners are viewable by everyone."
    ON weekly_winners FOR SELECT
    USING (true);

CREATE POLICY "Enable insert for service role only"
    ON weekly_winners FOR INSERT
    WITH CHECK (true);

CREATE POLICY "Enable update for service role only"
    ON weekly_winners FOR UPDATE
    USING (true);

-- Add weekly_wins column to profiles to track total weeks won
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS weekly_wins integer default 0;

