-- Create weekly_records table to track each user's record for each week
-- This provides an audit trail and source of truth for season totals

CREATE TABLE IF NOT EXISTS weekly_records (
  id bigint generated by default as identity primary key,
  user_id uuid references profiles(id) not null,
  week_start date not null,
  week_end date not null,
  wins integer default 0,
  losses integer default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  UNIQUE(user_id, week_start)
);

-- Enable RLS
ALTER TABLE weekly_records ENABLE ROW LEVEL SECURITY;

-- Everyone can read weekly records
CREATE POLICY "Weekly records are viewable by everyone"
  ON weekly_records FOR SELECT
  USING (true);

-- Only service role can insert/update (via automated scripts)
CREATE POLICY "Service role can manage weekly records"
  ON weekly_records FOR ALL
  USING (true);

-- Create index for faster queries
CREATE INDEX idx_weekly_records_user_week ON weekly_records(user_id, week_start);
CREATE INDEX idx_weekly_records_week ON weekly_records(week_start);

-- =====================================================
-- MIGRATE HISTORICAL DATA INTO weekly_records
-- =====================================================

-- Get user IDs (run SELECT first to verify)
-- SELECT id, username FROM profiles;

-- Week 1: Nov 10-16, 2025
INSERT INTO weekly_records (user_id, week_start, week_end, wins, losses)
SELECT id, '2025-11-10', '2025-11-16',
  CASE username 
    WHEN 'Jacoby' THEN 4
    WHEN 'Caden' THEN 8
    WHEN 'David ' THEN 6
  END,
  CASE username 
    WHEN 'Jacoby' THEN 11
    WHEN 'Caden' THEN 7
    WHEN 'David ' THEN 9
  END
FROM profiles
WHERE username IN ('Jacoby', 'Caden', 'David ')
ON CONFLICT (user_id, week_start) DO UPDATE SET
  wins = EXCLUDED.wins,
  losses = EXCLUDED.losses,
  updated_at = now();

-- Week 2: Nov 17-23, 2025
INSERT INTO weekly_records (user_id, week_start, week_end, wins, losses)
SELECT id, '2025-11-17', '2025-11-23',
  CASE username 
    WHEN 'Jacoby' THEN 12
    WHEN 'Caden' THEN 10
    WHEN 'David ' THEN 14
  END,
  CASE username 
    WHEN 'Jacoby' THEN 10
    WHEN 'Caden' THEN 12
    WHEN 'David ' THEN 8
  END
FROM profiles
WHERE username IN ('Jacoby', 'Caden', 'David ')
ON CONFLICT (user_id, week_start) DO UPDATE SET
  wins = EXCLUDED.wins,
  losses = EXCLUDED.losses,
  updated_at = now();

-- Week 3: Nov 24-30, 2025
INSERT INTO weekly_records (user_id, week_start, week_end, wins, losses)
SELECT id, '2025-11-24', '2025-11-30',
  CASE username 
    WHEN 'Jacoby' THEN 39
    WHEN 'Caden' THEN 33
    WHEN 'David ' THEN 35
  END,
  CASE username 
    WHEN 'Jacoby' THEN 28
    WHEN 'Caden' THEN 34
    WHEN 'David ' THEN 32
  END
FROM profiles
WHERE username IN ('Jacoby', 'Caden', 'David ')
ON CONFLICT (user_id, week_start) DO UPDATE SET
  wins = EXCLUDED.wins,
  losses = EXCLUDED.losses,
  updated_at = now();

-- Week 4: Dec 1-7, 2025 
-- Calculated from confirmed Week 4 ending totals minus Weeks 1-3:
--   Week 4 ending (confirmed): Jacoby 99-86, Caden 99-86, David 93-92
--   Weeks 1-3 paper totals:    Jacoby 55-49, Caden 51-53, David 55-49
--   Week 4 = ending - paper:   Jacoby 44-37, Caden 48-33, David 38-43
INSERT INTO weekly_records (user_id, week_start, week_end, wins, losses)
SELECT id, '2025-12-01', '2025-12-07',
  CASE username 
    WHEN 'Jacoby' THEN 44
    WHEN 'Caden' THEN 48
    WHEN 'David ' THEN 38
  END,
  CASE username 
    WHEN 'Jacoby' THEN 37
    WHEN 'Caden' THEN 33
    WHEN 'David ' THEN 43
  END
FROM profiles
WHERE username IN ('Jacoby', 'Caden', 'David ')
ON CONFLICT (user_id, week_start) DO UPDATE SET
  wins = EXCLUDED.wins,
  losses = EXCLUDED.losses,
  updated_at = now();

-- Week 5: Dec 8-14, 2025 (from database calculations)
INSERT INTO weekly_records (user_id, week_start, week_end, wins, losses)
SELECT id, '2025-12-08', '2025-12-14',
  CASE username 
    WHEN 'Jacoby' THEN 20
    WHEN 'Caden' THEN 13
    WHEN 'David ' THEN 14
  END,
  CASE username 
    WHEN 'Jacoby' THEN 7
    WHEN 'Caden' THEN 14
    WHEN 'David ' THEN 13
  END
FROM profiles
WHERE username IN ('Jacoby', 'Caden', 'David ')
ON CONFLICT (user_id, week_start) DO UPDATE SET
  wins = EXCLUDED.wins,
  losses = EXCLUDED.losses,
  updated_at = now();

-- =====================================================
-- VERIFY: Sum of weekly records should match season totals
-- =====================================================
SELECT 
  p.username,
  p.total_wins as stored_wins,
  p.total_losses as stored_losses,
  SUM(wr.wins) as calculated_wins,
  SUM(wr.losses) as calculated_losses,
  CASE WHEN p.total_wins = SUM(wr.wins) AND p.total_losses = SUM(wr.losses) 
    THEN '✓ Match' ELSE '✗ MISMATCH' END as status
FROM profiles p
LEFT JOIN weekly_records wr ON p.id = wr.user_id
GROUP BY p.id, p.username, p.total_wins, p.total_losses
ORDER BY p.total_wins DESC;

-- View all weekly records
SELECT 
  p.username,
  wr.week_start,
  wr.week_end,
  wr.wins,
  wr.losses
FROM weekly_records wr
JOIN profiles p ON wr.user_id = p.id
ORDER BY wr.week_start, p.username;
