-- Create profiles table
create table profiles (
  id uuid references auth.users not null primary key,
  email text,
  username text,
  total_points integer default 0,
  total_wins integer default 0,
  total_losses integer default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security (RLS)
alter table profiles enable row level security;

-- Create policies for profiles
create policy "Public profiles are viewable by everyone."
  on profiles for select
  using ( true );

create policy "Users can insert their own profile."
  on profiles for insert
  with check ( auth.uid() = id );

create policy "Users can update own profile."
  on profiles for update
  using ( auth.uid() = id );

-- Create games table
create table games (
  id bigint generated by default as identity primary key,
  team_a text not null,
  team_b text not null,
  start_time timestamp with time zone not null,
  result_a integer,
  result_b integer,
  status text default 'scheduled', -- 'scheduled', 'in_progress', 'finished'
  external_id text unique,
  spread text,
  team_a_record text,
  team_a_rank integer,
  team_b_record text,
  team_b_rank integer,
  team_a_abbrev text,
  team_b_abbrev text,
  game_date date, -- Stores the "scheduled date" (YYYY-MM-DD) to handle timezone issues
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS Policies for games
alter table games enable row level security;

create policy "Enable read access for all users"
on games for select
using (true);

create policy "Enable insert for all users"
on games for insert
with check (true);

create policy "Enable update for all users"
on games for update
using (true);

-- Create picks table
create table picks (
  id bigint generated by default as identity primary key,
  user_id uuid references profiles(id) not null,
  game_id bigint references games(id) not null,
  selected_team text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(user_id, game_id)
);

-- Enable RLS for picks
alter table picks enable row level security;

-- Create policies for picks
create policy "Users can view their own picks."
  on picks for select
  using ( auth.uid() = user_id );

create policy "Users can insert their own picks."
  on picks for insert
  with check ( auth.uid() = user_id );

create policy "Users can update their own picks."
  on picks for update
  using ( auth.uid() = user_id );

-- Create a trigger to handle new user signup
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, email, username)
  values (new.id, new.email, new.raw_user_meta_data->>'username');
  return new;
end;
$$ language plpgsql security definer;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();
